spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/restaurant;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true  # System.out? ?????? ?? SQL ??
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug  # logger? ?? ?????? ?? SQL ??
#    org.hibernate.orm.jdbc.bind: trace  # SQL ?? ????? ??? ?? -> spring-boot-data-source-decorator ??