INSERT INTO "USER" (ELITE, USER_ID, NAME) VALUES(true, 1, 'asdf');

INSERT INTO RESTAURANT (AVERAGE_RATING, LAT, LNG, RESTAURANT_ID, REVIEW_COUNT, ADDRESS, NAME) VALUES(4.5, 23.3, 23.3, 1, 4, '4', '4');

INSERT INTO REVIEW (RATING, RESTAURANT_ID, REVIEW_ID, USER_ID, REVIEW_TEXT) VALUES(4.0, 1, 1, 1, 'sdfsdf');